name: Deploy to AWS EC2
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Terraform directory structure
      - name: Prepare Terraform workspace
        run: |
          mkdir -p terraform
          # Only copy files that exist
          [ -f main.tf ] && cp main.tf terraform/
          [ -f variables.tf ] && cp variables.tf terraform/ || true
          [ -f terraform.tfvars ] && cp terraform.tfvars terraform/ || true
          ls -la terraform/  # Verify contents

      # Install Terraform (official method)
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"

      # Terraform steps
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve