name: Deploy to AWS EC2
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Terraform
        run: |
          # Remove any existing Terraform zip files
          rm -f terraform_*.zip
          
          # If terraform directory exists, remove it recursively
          if [ -d "terraform" ]; then
            rm -rf terraform
          fi
          
          # Download and install Terraform
          wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
          unzip -o terraform_1.5.7_linux_amd64.zip
          sudo install terraform /usr/local/bin/
          terraform --version

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd terraform
          terraform init
          terraform validate
          terraform apply -auto-approve