name: Deploy to AWS EC2
on:
  push:
    branches: [ "main" ]  # Triggers on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      # Checkout your code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Terraform
      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
          unzip terraform_1.5.7_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version  # Verify installation

      # Deploy with Terraform
      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd terraform
          terraform init
          terraform validate  # Check for errors
          terraform apply -auto-approve