name: Deploy to AWS EC2
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform  # All commands run in terraform directory

    steps:
      - uses: actions/checkout@v4

      - name: Create terraform directory
        run: |
          mkdir -p terraform
          cp main.tf terraform/  # Copy your Terraform config file
          cp variables.tf terraform/  # If you have variables file
          cp terraform.tfvars terraform/  # If you have vars file

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve